apiVersion: apps/v1
kind: Deployment
metadata:
  name: vordr
  namespace: vordr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vordr
  template:
    metadata:
      labels:
        app: vordr
    spec:
      containers:
        - name: vordr
          image: registry.digitalocean.com/vordr/vordr@sha256:ec6c25ff10c346a1146f50834df8802f5bd67604132c1f57f4f01ea50fbf4008
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: 'production'
            - name: LOGTAIL_API_KEY
              value: '{LOGTAIL_API_KEY}'
            - name: BETTERUPTIME_API_KEY
              value: '{BETTERUPTIME_API_KEY}'
      imagePullSecrets:
        - name: vordr-registry