apiVersion: v1
kind: Namespace
metadata:
  name: vordr
---
apiVersion: v1
kind: Secret
metadata:
  name: vordr-registry
  namespace: vordr
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kaWdpdGFsb2NlYW4uY29tIjp7ImF1dGgiOiJaRzl3WDNZeFh6SXpPVFpsWW1RNU1URTJZak0xTURabE9UY3hOVE01TnpNMVlqTTVZall3WVRsak5tVXlOMkppWldWbFpHTm1aamRsWXpreFlXTXlZalF3WW1FMk1ERTZaRzl3WDNZeFh6SXpPVFpsWW1RNU1URTJZak0xTURabE9UY3hOVE01TnpNMVlqTTVZall3WVRsak5tVXlOMkppWldWbFpHTm1aamRsWXpreFlXTXlZalF3WW1FMk1ERT0ifX19
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vordr
  namespace: vordr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vordr
  template:
    metadata:
      labels:
        app: vordr
    spec:
      containers:
        - name: vordr
          image: registry.digitalocean.com/vordr/vordr@sha256:dac3683c356f8c24540d01e539475865c6ac61e37fc7b32ebfa6a9554e88b083
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: 'production'
            - name: LOGTAIL_SOURCE_TOKEN
              value: '{LOGTAIL_SOURCE_TOKEN}'
            - name: BETTERUPTIME_API_KEY
              value: '{BETTERUPTIME_API_KEY}'
          resources:
            limits:
              cpu: 1
              memory: 1Gi
      imagePullSecrets:
        - name: vordr-registry