apiVersion: apps/v1
kind: Deployment
metadata:
  name: vordr
  namespace: vordr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vordr
  template:
    metadata:
      labels:
        app: vordr
    spec:
      containers:
        - name: vordr
          image: registry.digitalocean.com/vordr/vordr@sha256:ad475ae92fc24abb2437f88d85b5a74485b8e23600865e331847208bdabf7387
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: 'production'
            - name: LOGTAIL_API_KEY
              value: '{LOGTAIL_API_KEY}'
            - name: BETTERUPTIME_API_KEY
              value: '{BETTERUPTIME_API_KEY}'
          resources:
            limits:
              cpu: 1
              memory: 2Gi
      imagePullSecrets:
        - name: vordr-registry