apiVersion: v1
kind: Namespace
metadata:
  name: vordr
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vordr
  namespace: vordr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: thornode
  name: get-pods
rules:
  - apiGroups: [ '' ]
    resources: [ 'pods', 'pods/log' ]
    verbs: [ 'get', 'list' ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vordr
  namespace: thornode
subjects:
  - kind: ServiceAccount
    name: vordr
    namespace: vordr
roleRef:
  kind: Role
  name: get-pods
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vordr
  namespace: vordr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vordr
  template:
    metadata:
      labels:
        app: vordr
    spec:
      serviceAccountName: vordr
      containers:
        - name: vordr
          image: sourcap/vordr:release-1.4.0@sha256:8765e7bdd905404cc9b90aaf7dc2364f7abc751f4c66f85068e5c8426e54f460
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: 'production'
            - name: THORNODE_ADDRESS
              value: '{THORNODE_ADDRESS}'
            - name: BETTERUPTIME_API_KEY
              value: '{BETTERUPTIME_API_KEY}'
            - name: LOGTAIL_SOURCE_TOKEN
              value: '{LOGTAIL_SOURCE_TOKEN}'
          resources:
            limits:
              cpu: 1
              memory: 1Gi